services:
  ui:
     build: ./UI
     ports: 
     - "80:80"
     depends_on:
     - api
  api:
    build: ./Service
    ports:
    - "9000:9000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"